const PortOfEntryInitialState = {
  address: {
    country: "",
    region: "",
    city: "",
    postalCode: "",
    street: "",
    building: "",
  },
  age: 0,
  contactWithSuspected: false,
  contactWithConfirmed: false,
  dateOfBirth: "",
  dependents: [],
  email: "",
  firstName: "",
  flightNumber: "",
  hotelName: "",
  language: "",
  lastName: "",
  middleName: "",
  nationality: "",
  otherHotelName: "",
  passportNo: "",
  phoneNumber: "",
  seatNumber: "",
  sex: "",
  symptom: {
    fever: false,
    cough: false,
    shortnessOfBreath: false,
    fatigue: false,
    headache: false,
    runnyNose: false,
    feelingUnwell: false,
  },
  transitFrom: "",
  travelFrom: "",
  underlyingConditions: {
    chronicLungDisease: false,
    heartDisease: false,
    liverDisease: false,
    renalDisease: false,
    autoimmuneDisease: false,
    cancer: false,
    diabetes: false,
    hiv: false,
    pregnancy: false,
  },
};

export default PortOfEntryInitialState;
