const PortOfEntryInitialState = {
    firstName: "",
    middleName: "",
    lastName: "",
    sex: "",
    dateOfBirth: "",
    nationality: "",
    passportNo: "",
    travelFrom: "",
    phoneNumber: "",
    hotelName: "",
    flightNumber: "",
    seatNumber: "",
    transitFrom: "",
    occupation: "",
    fever: false,
    shortnessOfBreath: false,
    cough: false,
    dependents: [],
    otherHotelName: "",
    email: "",
    language: "",
    fatigue: false,
    underlyingConditions: {
        chronicLungDisease: false,
        heartDisease: false,
        liverDisease: false,
        renalDisease: false,
        autoimmuneDisease: false,
        cancer: false,
        diabetes: false,
        hiv: false,
        pregnancy: false,
    }, 
    haveSex: false,
    animalMarket: false,
    healthFacility: false 
 }

 export default PortOfEntryInitialState;
