const MedicalInitialState = {
    
    firstName: "",
    middleName: "",
    lastName: "",
    nationality: "",
    email: "",
    sex: "",
    age: 0,
    region: "",
    subcity: "",
    zone: "",
    woreda: "",
    kebele: "",
    houseNumber: "",
    phoneNumber: "",
    occupation: "",
    callDate: "",
    callerType: "",
    fever: false,
    cough: false,
    headache: false,
    runnyNose: false,
    feelingUnwell: false,
    shortnessOfBreath: false,
    bodyPain: false,
    travelHx: false,
    haveSex: false,
    animalMarket: false,
    healthFacility: false,
    receiverName: "",
    source: "",
    formStatus: "",
    fatigue: false,
    underlyingConditions: {
      chronicLungDisease: false,
      heartDisease: false,
      liverDisease: false,
      renalDisease: false,
      autoimmuneDisease: false,
      cancer: false,
      diabetes: false,
      hiv: false,
      pregnancy: false,
    },
  }

  export default MedicalInitialState;