export default {
  country: {
    Afghanistan: "አፍጋኒስታን",
    ÅlandIslands: "የአላንድ ደሴቶች",
    Albania: "አልባኒያ",
    Algeria: "አልጄሪያ",
    AmericanSamoa: "አሜሪካዊ ሳሞአ",
    AndorrA: "አንዶራ",
    Angola: "አንጎላ",
    Anguilla: "አንጉላ",
    Antarctica: "አንታርክቲካ",
    AntiguaandBarbuda: "አንቲጉአ እና ባርቡዳ",
    Argentina: "አርጀንቲና",
    Armenia: "አርሜኒያ",
    Aruba: "አሩባ",
    Australia: "አውስትራሊያ",
    Austria: "ኦስትራ",
    Azerbaijan: "አዘርባጃን",
    Bahamas: "ባሐማስ",
    Bahrain: "ባሃሬን",
    Bangladesh: "ባንግላድሽ",
    Barbados: "ባርባዶስ",
    Belarus: "ቤላሩስ",
    Belgium: "ቤልጄም",
    Belize: "ቤሊዜ",
    Benin: "ቤኒኒ",
    Bermuda: "ቤርሙዳ",
    Bhutan: "በሓቱን",
    Bolivia: "ቦሊቪያ",
    BosniaandHerzegovina: "ቦስኒያ እና ሔርዞጎቪያ",
    Botswana: "ቦትስዋና",
    BouvetIsland: "ቡuች ደሴት",
    Brazil: "ብራዚል",
    BritishIndianOceanTerritory: "የብሪታንያ ህንድ ውቅያኖስ ግዛት",
    BruneiDarussalam: "ብሩኒ ዳርሳላም",
    Bulgaria: "ቡልጋሪያ",
    BurkinaFaso: "ቡርክናፋሶ",
    Burundi: "ቡሩንዲ",
    Cambodia: "ካምቦዲያ",
    Cameroon: "ካሜሩን",
    Canada: "ካናዳ",
    CapeVerde: "ኬፕ ቬሪዴ",
    CaymanIslands: "ኬይማን አይስላንድ",
    CentralAfricanRepublic: "ሴንትራል አፍሪካ ሪፑቢሊክ",
    Chad: "ቻድ",
    Chile: "ቺሊ",
    China: "ቻይና",
    ChristmasIsland: "የገና ደሴት",
    CocosKeelingIslands: "ኮኮስ (ኬሊንግ) ደሴቶች",
    Colombia: "ኮሎምቢያ",
    Comoros: "ኮሞሮስ",
    Congo: "ኮንጎ",
    CongoTheDemocraticRepublicofthe: "ኮንጎ ዲሞክራቲክ ሪፐብሊክ",
    CookIslands: "ኩክ አይስላንድስ",
    CostaRica: "ኮስታ ሪካ",
    CoteDIvoire: "ኮትዲቫር",
    Croatia: "ክሮሽያ",
    Cuba: "ኩባ",
    Cyprus: "ቆጵሮስ",
    CzechRepublic: "ቼክ ሪፐብሊክ",
    Denmark: "ዴንማሪክ",
    Djibouti: "ጅቡቲ",
    Dominica: "ዶሚኒካ",
    DominicanRepublic: "ዶሚኒካን ሪፐብሊክ",
    Ecuador: "ኢኳዶር",
    Egypt: "ግብጽ",
    ElSalvador: "ኤልሳልቫዶር",
    EquatorialGuinea: "ኢኳቶሪያል ጊኒ",
    Eritrea: "ኤርትሪያ",
    Estonia: "ኢስቶኒያ",
    Ethiopia: "ኢትዮጵያ",
    FalklandIslandsMalvinas: "የፎልክላንድ ደሴቶች (ማልቪናስ)",
    FaroeIslands: "ፋሮ ደሴቶች",
    Fiji: "ፊጂ",
    Finland: "ፊኒላንድ",
    France: "ፈረንሳይ",
    FrenchGuiana: "ፈረንሣይ ጉያና",
    FrenchPolynesia: "የፈረንሣይ ፖሊኔዥያ ",
    FrenchSouthernTerritories: "የፈረንሳይ ደቡባዊ ግዛቶች",
    Gabon: "ጋቦን",
    Gambia: "ጋምቢያ",
    Georgia: "ጆርጂያ",
    Germany: "ጀርመን",
    Ghana: "ጋና",
    Gibraltar: "ጊብራልታር",
    Greece: "ግሪክ",
    Greenland: "ግሪንላንድ",
    Grenada: "ግሪንዳዳ",
    Guadeloupe: "ጉደሎፕ",
    Guam: "ጉአሜ",
    Guatemala: "ጓቴማላ",
    Guernsey: "Ernርኒ",
    Guinea: "ጊኒ",
    GuineaBissau: "ጊኒ - ቢሳው",
    Guyana: "ጉያና",
    Haiti: "ሓይቲ",
    HeardIslandandMcdonaldIslands: "Ardርድ አይስላንድ እና ማክዶናልድ ደሴቶች",
    HolySeeVaticanCityState: "ቅዱስ ዕይታ (የቫቲካን ከተማ ግዛት)",
    Honduras: "ሆንዱራስ",
    HongKong: "ሆንግ ኮንግ",
    Hungary: "ሃንጋሪ",
    Iceland: "አይስላንድ",
    India: "ሕንድ",
    Indonesia: "ኢንዶኔዥያ",
    IranIslamicRepublicOf: "ኢራን , እስላማዊ ሪፐብሊክ",
    Iraq: "ኢራቅ",
    Ireland: "አይርላድ",
    IsleofMan: "አይስ የሰው",
    Israel: "እስራኤል",
    Italy: "ጣሊያን",
    Jamaica: "ጃማይካ",
    Japan: "ጃፓን",
    Jersey: "ጀርሲ",
    Jordan: "ዮርዳኖስ",
    Kazakhstan: "ካዛክስታን",
    Kenya: "ኬንያ",
    Kiribati: "ኪሪባቲ",
    KoreaDemocraticPeopleSRepublicof: "ኮሪያ , የዴሞክራሲያዊ ህዝብ ሪፐብሊክ",
    KoreaRepublicof: "ኮሪያ , ሪፐብሊክ",
    Kuwait: "ኵዌት",
    Kyrgyzstan: "ክይርጋዝስታን",
    LaoPeopleSDemocraticRepublic: "ላኦ ሰዎች ዲሞክራሲያዊ ሪፐብሊክ",
    Latvia: "ላቲቪያ",
    Lebanon: "ሊባኖስ",
    Lesotho: "ሌስቶ",
    Liberia: "ላይቤሪያ",
    LibyanArabJamahiriya: "ሊቢያ አረብ ጃማሂሪያ",
    Liechtenstein: "ለይችቴንስቴይን",
    Lithuania: "ሊቱአኒያ",
    Luxembourg: "ሉዘምቤርግ",
    Macao: "ማኮዎ",
    MacedoniaTheFormerYugoslavRepublicof: "መቄዶንያ , የቀድሞው የዩጎዝላቪያ ሪፐብሊክ",
    Madagascar: "ማዳጋስካር",
    Malawi: "ማላዊ",
    Malaysia: "ማሌዥያ",
    Maldives: "ማልዲቬስ",
    Mali: "ማሊ",
    Malta: "ማልታ",
    MarshallIslands: "ማርሻል አይስላንድ",
    Martinique: "ማርቲኒክ",
    Mauritania: "ሞሪታኒያ",
    Mauritius: "ሞሪሼስ",
    Mayotte: "ማዮትት",
    Mexico: "ሜክስኮ",
    MicronesiaFederatedStatesof: "ማይክሮኔዥያ , ፌዴራል መንግስታት",
    MoldovaRepublicof: "ሞልዶቫ , ሪፐብሊክ",
    Monaco: "ሞናኮ",
    Mongolia: "ሞንጎሊያ",
    Montserrat: "ሞንትሴራት",
    Morocco: "ሞሮኮ",
    Mozambique: "ሞዛምቢክ",
    Myanmar: "ማይንማር",
    Namibia: "ናምቢያ",
    Nauru: "ናኡሩ",
    Nepal: "ኔፓል",
    Netherlands: "ኔዜሪላንድ",
    NetherlandsAntilles: "ኔዘርላንድስ አንቲለስ",
    NewCaledonia: "ኒው ካሌዶኒያ",
    NewZealand: "ኒውዚላንድ",
    Nicaragua: "ኒካራጉአ",
    Niger: "ኒጀር",
    Nigeria: "ናይጄሪያ",
    Niue: "ኒይኡ",
    NorfolkIsland: "ኖርፎልክ አይስላንድስ",
    NorthernMarianaIslands: "የሰሜናዊ ማሪያና አይስላንድስ",
    Norway: "ኖርዌይ",
    Oman: "ኦማን",
    Pakistan: "ፓኪስታን",
    Palau: "ፓላኡ",
    PalestinianTerritoryOccupied: "የፍልስጤም ግዛት , የተያዘ",
    Panama: "ፓናማ",
    PapuaNewGuinea: "ፓፓዋ ኒው ጊኒ",
    Paraguay: "ፓራጓይ",
    Peru: "ፔሩ",
    Philippines: "ፊሊፕንሲ",
    Pitcairn: "ፒትካሪን",
    Poland: "ፖላንድ",
    Portugal: "ፖርቹጋል",
    PuertoRico: "ፖረቶ ሪኮ",
    Qatar: "ኳታር",
    Reunion: "ሬዩኒየን",
    Romania: "ሮማኒያ",
    RussianFederation: "የራሺያ ፌዴሬሽን",
    RWANDA: "ሩዋንዳ",
    SaintHelena: "ሰይንት ሄሌና",
    SaintKittsandNevis: "ሰይንት ኪትስ እና ኔቪስ",
    SaintLucia: "ሰይንት ሉካስ",
    SaintPierreandMiquelon: "ቅዱስ ፒየር እና ሚqueሎን",
    SaintVincentandtheGrenadines: "ሰይንት ቪንሴንት እና ጀሬናዲኔስ",
    Samoa: "ሳሞአ",
    SanMarino: "ሳን ማሪኖ",
    SaoTomeandPrincipe: "ሳኦ ቶሜ እና ፕሪንቺፔ",
    SaudiArabia: "ሳውዲ አረብያ",
    Senegal: "ሴኔጋል",
    SerbiaandMontenegro: "ሰርቢያ እና ሞንቴኔግሮ",
    Seychelles: "ሲሼልስ",
    SierraLeone: "ሰራሊዮን",
    Singapore: "ስንጋፖር",
    Slovakia: "ስሎቫኒካ",
    Slovenia: "ስሎቫኒያ",
    SolomonIslands: "የሰሎሞን አይስላንድስ",
    Somalia: "ሶማሊያ",
    SouthAfrica: "ደቡብ አፍሪካ",
    SouthGeorgiaandtheSouthSandwichIslands: "ደቡብ ጆርጂያ እና የደቡብ ሳንድዊች ደሴቶች",
    Spain: "ስፔን",
    SriLanka: "ስሪ ላንካ",
    Sudan: "ሱዳን",
    Suriname: "ሱሪናሜ",
    SvalbardandJanMayen: "ስቫልባር እና ጃን ማየን",
    Swaziland: "ስዋዝላድ",
    Sweden: "ስዊዲን",
    Switzerland: "ስዊዘሪላንድ",
    SyrianArabRepublic: "የሶሪያ አረብ ሪፐብሊክ",
    TaiwanProvinceofChina: "ታይዋን , የቻይና ግዛት",
    Tajikistan: "ታጂኪስታን",
    TanzaniaUnitedRepublicof: "ታንዛኒያ , የተባበሩት መንግስታት",
    Thailand: "ታይላንድ",
    TimorLeste: "ቲሞር-ሌስት",
    Togo: "መሄድ",
    Tokelau: "ቶኬላኡ",
    Tonga: "ቶንጋ",
    TrinidadandTobago: "ትሪኒዳድ እና ቶባጎ",
    Tunisia: "ቱንሲያ",
    Turkey: "ቱሪክ",
    Turkmenistan: "ቱርክሜኒስታን",
    TurksandCaicosIslands: "ቱርኮች እና የካኢኮስ ደሴቶች",
    Tuvalu: "ቱቫሉ",
    Uganda: "ኡጋንዳ",
    Ukraine: "ዩክሬን",
    UnitedArabEmirates: "ዩናይቲድ አራብ ኤሚራትስ",
    UnitedKingdom: "እንግሊዝ",
    UnitedStates: "የተባበሩት መንግስታት",
    UnitedStatesMinorOutlyingIslands: "የዩናይትድ ስቴትስ ትናንሽ ሩቅ ደሴቶች",
    Uruguay: "ኡራጋይ",
    Uzbekistan: "ኡዝቤክስታን",
    Vanuatu: "ቫኑአቱ",
    Venezuela: "ቨንዙዋላ",
    VietNam: "ቪትናም",
    VirginIslandsBritish: "ድንግል ደሴቶች , ብሪታንያ",
    VirginIslandsUS: "ድንግል ደሴቶች , አሜሪካ",
    WallisandFutuna: "ዎሊስ እና ፉቱና",
    WesternSahara: "ምዕራባዊ ሳሃራ",
    Yemen: "የመን",
    Zambia: "ዛምቢያ",
    Zimbabwe: "ዝምባቡዌ",
  },
  nationality: {
    afghan: "አፍጋኒስታን",
    albanian: "አልበንያኛ",
    algerian: "አልጄሪያ",
    american: "አሜሪካዊው ",
    argentinian: "አርጀንቲና",
    australian: "አውስትራሊያዊ",
    austrian: "ኦስትሪያ",
    bangladeshi: "ባንግላዴሽ",
    batswana: "ብራዚላዊ",
    belgian: "ቤልጂየም",
    bolivian: "ቦሊቪያኛ",
    brazilian: "ብራዚላዊ",
    British: "ብሪቲሽ",
    bulgarian: "ቡልጋርያኛ",
    cambodian: "ካምቦዲያኛ",
    cameroonian: "ካሜሩንያንኛ",
    canadian: "ካናዳዊ",
    chilean: "ቺሊኛ",
    chinese: "ቻይንኛ",
    colombian: "ኮሎምቢያኛ",
    costaRican: "ኮስታ ሪካ",
    croatian: "ክሮኤሽያን",
    cuban: "ኩባ",
    czech: "ቼክ",
    danish: "ዳኒሽ",
    dominican: "ዶሚኒካን",
    dutch: "ደች",
    ecuadorian: "ኢኳዶር",
    egyptian: "ግብፃዊ",
    Emirati: "ኢሚራቲ",
    english: "እንግሊዝኛ",
    estonian: "ኢስቶኒያን",
    ethiopian: "ኢትዮጵያዊ",
    fijian: "ፊጂያን",
    finnish: "ፊኒሽ",
    french: "ፈረንሳይኛ",
    german: "ጀርመንኛ",
    ghanaian: "ጋናኛ",
    greek: "ግሪክኛ",
    guatemalan: "ጓቲማላን",
    haitian: "ሄይቲኛ",
    honduran: "የሆንዱራን",
    hungarian: "ሃንጋሪያን",
    icelandic: "አይስላንዲ ክ",
    indian: "ህንድ",
    indonesian: "ኢንዶኔዥያን",
    iranian: "ኢራናዊ",
    iraqi: "ኢራቃዊ",
    irish: "አይሪሽ",
    israeli: "እስራኤል",
    italian: "ጣሊያንኛ",
    jamaican: "ጃማይካዊ",
    japanese: "ጃፓንኛ",
    jordanian: "ዮርዳኖስ",
    kenyan: "ኬንያ",
    korean: "ኮሪያኛ",
    kuwaiti: "ኩዌት",
    lao: "ላኦ",
    latvian: "ላትቪያን",
    lebanese: "ሊባኖሳዊ",
    libyan: "ሊቢያ",
    lithuanian: "ሊቱኒያን",
    malagasy: "ማላጊዝ",
    malaysian: "ማሌsianያ",
    malian: "ማሊያንኛ",
    maltese: "ማልትስ",
    mexican: "ሜክሲኮኛ",
    mongolian: "ሞኒጎሊያን",
    moroccan: "ሞሮኮኛ",
    mozambican: "ሞዛምቢክኛ",
    namibian: "ናሚቢያኛ",
    nepalese: "ኔፓል",
    newzealand: "ኒውዚላንድ",
    nicaraguan: "ኒካራጓን",
    nigerian: "ናይጄሪያ",
    norwegian: "ኖርወይኛ",
    pakistani: "ፓኪስታን",
    panamanian: "ፓናማኒያን",
    paraguayan: "ፓራጓይ",
    peruvian: "ፔሩቪያኛ",
    philippine: "ፊሊፒንስ",
    polish: "ፖሊሽ",
    portuguese: "ፖርቹጋልኛ",
    romanian: "ሮማንያን",
    russian: "ራሺያኛ",
    salvadorian: "ሳልቫዶሪያን",
    saudi: "ሳዑዲ",
    scottish: "ስኮትላንድኛ",
    senegalese: "ሴኔጋሌ",
    serbian: "ሰሪቢያን",
    singaporean: "ሲንጋፖር",
    slovak: "ስሎቫክ",
    southafrican: "ደቡብ አፍሪካ",
    spanish: "ስፓንኛ",
    srilankan: "ስሪላንካን",
    sudanese: "ሱዳናዊ",
    swedish: "ስዊድንኛ",
    swiss: "ስዊስ",
    syrian: "ሶሪያ",
    taiwanese: "ታይዋንኛ",
    tajikistani: "ታጂኪስታን",
    thai: "ታይ",
    tongan: "ቶንጋን",
    tunisian: "ቱኒዚያዊ",
    turkish: "ቱሪክሽ",
    ukrainian: "ዩክሬንያን",
    uruguayan: "ኡራጓይኛ",
    venezuelan: "ቨንዙዋላ",
    vietnamese: "ቪትናሜሴ",
    welsh: "ዋልሽ",
    zambian: "ዛምቢያኛ",
    zimbabwean: "ዚምባብዌኛ",
  },
  city: {
    AddisAbaba: "አዲስ አበባ",
    Mekelle: "መቀሌ",
    Gondar: "ጎንደር",
    Adama: "አዳም",
    Hawassa: "እነሱ አያምኑም",
    BahirDar: "ባህር ዳር",
    DireDawa: "ድሬ መድኃኒት",
    Sodo: "ሶዶ",
    Dessie: "ደሴ",
    Jimma: "ጅማ",
    Jijiga: "ጅጅጋ",
    Shashamane: "ሻሸመኔ",
    Bishoftu: "ቢሾፍቱ",
    ArbaMinch: "አርባምንጭ",
    Hosaena: "ሆሳዕና",
    Harar: "ሐረር",
    Dilla: "ዲላ",
    Nekemte: "ነቀምቴ",
    DebreBirhan: "ደብረብርሃን",
    Asella: "አሴላ",
    DebreMarkos: "ደብረ ማርቆስ",
    Kombolcha: "ኮምቦልቻ",
    DebreTabor: "ደብረ ታቦር",
    Adigrat: "አድጊራት",
    Woldiya: "ወልድያ",
    Sebeta: "ሰበታ ",
    Burayu: "ቡሩይ",
    Shire: "ሽሬ",
    Ambo: "አምቦ",
    ArsiNegele: "አርሲ ነገሌ",
    Aksum: "አክሱም",
    Gambela: "ያዝ",
    BaleRobe: "ባሌ ሮቤ",
    Butajira: "ቡታጅራ ",
    Ziway: "ዝዋይ",
    Adwa: "አድዋ",
  },
  subcity: {
    addisKetema: "አዲስ ከተማ",
    akakiKality: "አቃቂ ቃሊቲ",
    arada: "አራዳ",
    bole: "ቦሌ",
    gulele: "ጉለሌ",
    kirkos: "ቂርቆስ",
    kolfe: "ኮልፌ",
    lideta: "ልደታ",
    nifasSilkLafto: "ንፋስ ስልክ ላፍቶ",
    yeka: "የካ",
  },
  region: {
    addisAbaba: "አዲስ አበባ",
    afar: "አፋር",
    amhara: "አማራ",
    benishangul: "ቤንሻንጉል ጉሙዝ",
    direDawa: "ድሬ ዳዋ",
    gambella: "ጋምቤላ",
    harari: "ሐረር",
    oromia: "ኦሮሚያ",
    somali: "ሶማሌ",
    southern: "የደቡብ ብሔር ብሔረሰቦችና ህዝቦች ክልል",
    tigray: "ትግራይ",
  },
};
