export default {
  country: {
    Afghanistan: "Afghanistan",
    ÅlandIslands: "Åland Islands",
    Albania: "Albania",
    Algeria: "Algeria",
    AmericanSamoa: "American Samoa",
    AndorrA: "AndorrA",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarctica",
    AntiguaandBarbuda: "Antigua and Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenia",
    Aruba: "Aruba",
    Australia: "Australia",
    Austria: "Austria",
    Azerbaijan: "Azerbaijan",
    Bahamas: "Bahamas",
    Bahrain: "Bahrain",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Belarus",
    Belgium: "Belgium",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermuda",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    BosniaandHerzegovina: "Bosnia and Herzegovina",
    Botswana: "Botswana",
    BouvetIsland: "Bouvet Island",
    Brazil: "Brazil",
    BritishIndianOceanTerritory: "British Indian Ocean Territory",
    BruneiDarussalam: "Brunei Darussalam",
    Bulgaria: "Bulgaria",
    BurkinaFaso: "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Cambodia",
    Cameroon: "Cameroon",
    Canada: "Canada",
    CapeVerde: "Cape Verde",
    CaymanIslands: "Cayman Islands",
    CentralAfricanRepublic: "Central African Republic",
    Chad: "Chad",
    Chile: "Chile",
    China: "China",
    ChristmasIsland: "Christmas Island",
    CocosKeelingIslands: "Cocos (Keeling) Islands",
    Colombia: "Colombia",
    Comoros: "Comoros",
    Congo: "Congo",
    CongoTheDemocraticRepublicofthe: "Congo, The Democratic Republic of the",
    CookIslands: "Cook Islands",
    CostaRica: "Costa Rica",
    CoteDIvoire: "Cote D'Ivoire",
    Croatia: "Croatia",
    Cuba: "Cuba",
    Cyprus: "Cyprus",
    CzechRepublic: "Czech Republic",
    Denmark: "Denmark",
    Djibouti: "Djibouti",
    Dominica: "Dominica",
    DominicanRepublic: "Dominican Republic",
    Ecuador: "Ecuador",
    Egypt: "Egypt",
    ElSalvador: "El Salvador",
    EquatorialGuinea: "Equatorial Guinea",
    Eritrea: "Eritrea",
    Estonia: "Estonia",
    Ethiopia: "Ethiopia",
    FalklandIslandsMalvinas: "Falkland Islands (Malvinas)",
    FaroeIslands: "Faroe Islands",
    Fiji: "Fiji",
    Finland: "Finland",
    France: "France",
    FrenchGuiana: "French Guiana",
    FrenchPolynesia: "French Polynesia",
    FrenchSouthernTerritories: "French Southern Territories",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgia",
    Germany: "Germany",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Greece",
    Greenland: "Greenland",
    Grenada: "Grenada",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guinea",
    GuineaBissau: "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    HeardIslandandMcdonaldIslands: "Heard Island and Mcdonald Islands",
    HolySeeVaticanCityState: "Holy See (Vatican City State)",
    Honduras: "Honduras",
    HongKong: "Hong Kong",
    Hungary: "Hungary",
    Iceland: "Iceland",
    India: "India",
    Indonesia: "Indonesia",
    IranIslamicRepublicOf: "Iran, Islamic Republic Of",
    Iraq: "Iraq",
    Ireland: "Ireland",
    IsleofMan: "Isle of Man",
    Israel: "Israel",
    Italy: "Italy",
    Jamaica: "Jamaica",
    Japan: "Japan",
    Jersey: "Jersey",
    Jordan: "Jordan",
    Kazakhstan: "Kazakhstan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    KoreaDemocraticPeopleSRepublicof: "Korea, Democratic People'S Republic of",
    KoreaRepublicof: "Korea, Republic of",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kyrgyzstan",
    LaoPeopleSDemocraticRepublic: "Lao People'S Democratic Republic",
    Latvia: "Latvia",
    Lebanon: "Lebanon",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    LibyanArabJamahiriya: "Libyan Arab Jamahiriya",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lithuania",
    Luxembourg: "Luxembourg",
    Macao: "Macao",
    MacedoniaTheFormerYugoslavRepublicof:
      "Macedonia, The Former Yugoslav Republic of",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Maldives",
    Mali: "Mali",
    Malta: "Malta",
    MarshallIslands: "Marshall Islands",
    Martinique: "Martinique",
    Mauritania: "Mauritania",
    Mauritius: "Mauritius",
    Mayotte: "Mayotte",
    Mexico: "Mexico",
    MicronesiaFederatedStatesof: "Micronesia, Federated States of",
    MoldovaRepublicof: "Moldova, Republic of",
    Monaco: "Monaco",
    Mongolia: "Mongolia",
    Montserrat: "Montserrat",
    Morocco: "Morocco",
    Mozambique: "Mozambique",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Netherlands",
    NetherlandsAntilles: "Netherlands Antilles",
    NewCaledonia: "New Caledonia",
    NewZealand: "New Zealand",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Niue",
    NorfolkIsland: "Norfolk Island",
    NorthernMarianaIslands: "Northern Mariana Islands",
    Norway: "Norway",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    PalestinianTerritoryOccupied: "Palestinian Territory, Occupied",
    Panama: "Panama",
    PapuaNewGuinea: "Papua New Guinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Philippines",
    Pitcairn: "Pitcairn",
    Poland: "Poland",
    Portugal: "Portugal",
    PuertoRico: "Puerto Rico",
    Qatar: "Qatar",
    Reunion: "Reunion",
    Romania: "Romania",
    RussianFederation: "Russian Federation",
    RWANDA: "RWANDA",
    SaintHelena: "Saint Helena",
    SaintKittsandNevis: "Saint Kitts and Nevis",
    SaintLucia: "Saint Lucia",
    SaintPierreandMiquelon: "Saint Pierre and Miquelon",
    SaintVincentandtheGrenadines: "Saint Vincent and the Grenadines",
    Samoa: "Samoa",
    SanMarino: "San Marino",
    SaoTomeandPrincipe: "Sao Tome and Principe",
    SaudiArabia: "Saudi Arabia",
    Senegal: "Senegal",
    SerbiaandMontenegro: "Serbia and Montenegro",
    Seychelles: "Seychelles",
    SierraLeone: "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slovakia",
    Slovenia: "Slovenia",
    SolomonIslands: "Solomon Islands",
    Somalia: "Somalia",
    SouthAfrica: "South Africa",
    SouthGeorgiaandtheSouthSandwichIslands:
      "South Georgia and the South Sandwich Islands",
    Spain: "Spain",
    SriLanka: "Sri Lanka",
    Sudan: "Sudan",
    Suriname: "Suriname",
    SvalbardandJanMayen: "Svalbard and Jan Mayen",
    Swaziland: "Swaziland",
    Sweden: "Sweden",
    Switzerland: "Switzerland",
    SyrianArabRepublic: "Syrian Arab Republic",
    TaiwanProvinceofChina: "Taiwan, Province of China",
    Tajikistan: "Tajikistan",
    TanzaniaUnitedRepublicof: "Tanzania, United Republic of",
    Thailand: "Thailand",
    TimorLeste: "Timor-Leste",
    Togo: "Togo",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    TrinidadandTobago: "Trinidad and Tobago",
    Tunisia: "Tunisia",
    Turkey: "Turkey",
    Turkmenistan: "Turkmenistan",
    TurksandCaicosIslands: "Turks and Caicos Islands",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukraine",
    UnitedArabEmirates: "United Arab Emirates",
    UnitedKingdom: "United Kingdom",
    UnitedStates: "United States",
    UnitedStatesMinorOutlyingIslands: "United States Minor Outlying Islands",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    VietNam: "Viet Nam",
    VirginIslandsBritish: "Virgin Islands, British",
    VirginIslandsUS: "Virgin Islands, U.S.",
    WallisandFutuna: "Wallis and Futuna",
    WesternSahara: "Western Sahara",
    Yemen: "Yemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
  },
  nationality: {
    afghan: "Afghan",
    albanian: "Albanian",
    algerian: "Algerian",
    american: "American ",
    argentinian: "Argentine",
    australian: "Australian",
    austrian: "Austrian",
    bangladeshi: "Bangladeshi",
    batswana: "Batswana",
    belgian: "Belgian",
    bolivian: "Bolivian",
    brazilian: "Brazilian",
    British: "British",
    bulgarian: "Bulgarian",
    cambodian: "Cambodian",
    cameroonian: "Cameroonian",
    canadian: "Canadian",
    chilean: "Chilean",
    chinese: "Chinese",
    colombian: "Colombian",
    costaRican: "Costa Rican",
    croatian: "Croatian",
    cuban: "Cuban",
    czech: "Czech",
    danish: "Danish",
    dominican: "Dominican",
    dutch: "Dutch",
    ecuadorian: "Ecuadorian",
    egyptian: "Egyptian",
    Emirati: "Emirati",
    english: "English",
    estonian: "Estonian",
    ethiopian: "Ethiopian",
    fijian: "Fijian",
    finnish: "Finnish",
    french: "French",
    german: "German",
    ghanaian: "Ghanaian",
    greek: "Greek",
    guatemalan: "Guatemalan",
    haitian: "Haitian",
    honduran: "Honduran",
    hungarian: "Hungarian",
    icelandic: "Icelandic",
    indian: "Indian",
    indonesian: "Indonesian",
    iranian: "Iranian",
    iraqi: "Iraqi",
    irish: "Irish",
    israeli: "Israeli",
    italian: "Italian",
    jamaican: "Jamaican",
    japanese: "Japanese",
    jordanian: "Jordanian",
    kenyan: "Kenyan",
    korean: "Korean",
    kuwaiti: "Kuwaiti",
    lao: "Lao",
    latvian: "Latvian",
    lebanese: "Lebanese",
    libyan: "Libyan",
    lithuanian: "Lithuanian",
    malagasy: "Malagasy",
    malaysian: "Malaysian",
    malian: "Malian",
    maltese: "Maltese",
    mexican: "Mexican",
    mongolian: "Mongolian",
    moroccan: "Moroccan",
    mozambican: "Mozambican",
    namibian: "Namibian",
    nepalese: "Nepalese",
    newzealand: "New Zealand",
    nicaraguan: "Nicaraguan",
    nigerian: "Nigerian",
    norwegian: "Norwegian",
    pakistani: "Pakistani",
    panamanian: "Panamanian",
    paraguayan: "Paraguayan",
    peruvian: "Peruvian",
    philippine: "Philippine",
    polish: "Polish",
    portuguese: "Portuguese",
    romanian: "Romanian",
    russian: "Russian",
    salvadorian: "Salvadorian",
    saudi: "Saudi",
    scottish: "Scottish",
    senegalese: "Senegalese",
    serbian: "Serbian",
    singaporean: "Singaporean",
    slovak: "Slovak",
    southafrican: "South African",
    spanish: "Spanish",
    srilankan: "Sri Lankan",
    sudanese: "Sudanese",
    swedish: "Swedish",
    swiss: "Swiss",
    syrian: "Syrian",
    taiwanese: "Taiwanese",
    tajikistani: "Tajikistani",
    thai: "Thai",
    tongan: "Tongan",
    tunisian: "Tunisian",
    turkish: "Turkish",
    ukrainian: "Ukrainian",
    uruguayan: "Uruguayan",
    venezuelan: "Venezuelan",
    vietnamese: "Vietnamese",
    welsh: "Welsh",
    zambian: "Zambian",
    zimbabwean: "Zimbabwean",
  },
  city: {
    AddisAbaba: "Addis Ababa",
    Mekelle: "Mekelle",
    Gondar: "Gondar",
    Adama: "Adama",
    Hawassa: "Hawassa",
    BahirDar: "Bahir Dar",
    DireDawa: "Dire Dawa",
    Sodo: "Sodo",
    Dessie: "Dessie",
    Jimma: "Jimma",
    Jijiga: "Jijiga",
    Shashamane: "Shashamane",
    Bishoftu: "Bishoftu",
    ArbaMinch: "Arba Minch",
    Hosaena: "Hosaena",
    Harar: "Harar",
    Dilla: "Dilla",
    Nekemte: "Nekemte",
    DebreBirhan: "Debre Birhan",
    Asella: "Asella",
    DebreMarkos: "Debre Markos",
    Kombolcha: "Kombolcha",
    DebreTabor: "Debre Tabor",
    Adigrat: "Adigrat",
    Woldiya: "Woldiya",
    Sebeta: "Sebeta",
    Burayu: "Burayu",
    Shire: "Shire",
    Ambo: "Ambo",
    ArsiNegele: "Arsi Negele",
    Aksum: "Aksum",
    Gambela: "Gambela",
    BaleRobe: "Bale Robe",
    Butajira: "Butajira",
    Ziway: "Ziway",
    Adwa: "Adwa",
  },
  subcity: {
    addisKetema: "Addis Ketema",
    akakiKality: "Akaki Kality",
    arada: "Arada",
    bole: "Bole",
    gulele: "Gulele",
    kirkos: "Kirkos",
    kolfe: "Kolfe",
    lideta: "Lideta",
    nifasSilkLafto: "Nifas Silk Lafto",
    yeka: "Yeka",
  },
  region: {
    addisAbaba: "Addis Ababa",
    afar: "Afar",
    amhara: "Amhara",
    benishangul: "Benishangul-Gumuz",
    direDawa: "Dire Dawa",
    gambella: "Gambella",
    harari: "Harari",
    oromia: "Oromia",
    somali: "Somali",
    southern: "Southern Nations, Nationalities, and Peoples",
    tigray: "Tigray",
  },
};
