export default {
  language: {
    label: "ቋንቋ",
    english: "እንግሊዘኛ",
    amharic: "አማርኛ",
    oromo: "ኦሮምኛ",
  },
  firstName: "ስም",
  middleName: "የአባት ስም",
  lastName: "የአያት ስም",
  nationality: {
    label: "ዜግነት",
    afghan: "አፍጋኒስታን",
    albanian: "አልበንያኛ",
    algerian: "አልጄሪያ",
    argentinian: "አርጀንቲና",
    australian: "አውስትራሊያዊ",
    austrian: "ኦስትሪያ",
    bangladeshi: "ባንግላዴሽ",
    belgian: "ቤልጂየም",
    bolivian: "ቦሊቪያኛ",
    batswana: "ብራዚላዊ",
    brazilian: "ብራዚላዊ",
    bulgarian: "ቡልጋርያኛ",
    cambodian: "ካምቦዲያኛ",
    cameroonian: "ካሜሩንያንኛ",
    canadian: "ካናዳዊ",
    chilean: "ቺሊኛ",
    chinese: "ቻይንኛ",
    colombian: "ኮሎምቢያኛ",
    costaRican: "ኮስታ ሪካ",
    croatian: "ክሮኤሽያን",
    cuban: "ኩባ",
    czech: "ቼክ",
    danish: "ዳኒሽ",
    dominican: "ዶሚኒካን",
    ecuadorian: "ኢኳዶር",
    egyptian: "ግብፃዊ",
    salvadorian: "ሳልቫዶሪያን",
    english: "እንግሊዝኛ",
    estonian: "ኢስቶኒያን",
    ethiopian: "ኢትዮጵያዊ",
    fijian: "ፊጂያን",
    finnish: "ፊኒሽ",
    french: "ፈረንሳይኛ",
    german: "ጀርመንኛ",
    ghanaian: "ጋናኛ",
    greek: "ግሪክኛ",
    guatemalan: "ጓቲማላን",
    haitian: "ሄይቲኛ",
    honduran: "የሆንዱራን",
    hungarian: "ሃንጋሪያን",
    icelandic: "አይስላንዲ ክ",
    indian: "ህንድ",
    indonesian: "ኢንዶኔዥያን",
    iranian: "ኢራናዊ",
    iraqi: "ኢራቃዊ",
    irish: "አይሪሽ",
    israeli: "እስራኤል",
    italian: "ጣሊያንኛ",
    jamaican: "ጃማይካዊ",
    japanese: "ጃፓንኛ",
    jordanian: "ዮርዳኖስ",
    kenyan: "ኬንያ",
    kuwaiti: "ኩዌት",
    lao: "ላኦ",
    latvian: "ላትቪያን",
    lebanese: "ሊባኖሳዊ",
    libyan: "ሊቢያ",
    lithuanian: "ሊቱኒያን",
    malagasy: "ማላጊዝ",
    malaysian: "ማሌsianያ",
    malian: "ማሊያንኛ",
    maltese: "ማልትስ",
    mexican: "ሜክሲኮኛ",
    mongolian: "ሞኒጎሊያን",
    moroccan: "ሞሮኮኛ",
    mozambican: "ሞዛምቢክኛ",
    namibian: "ናሚቢያኛ",
    nepalese: "ኔፓል",
    dutch: "ደች",
    newzealand: "ኒውዚላንድ",
    nicaraguan: "ኒካራጓን",
    nigerian: "ናይጄሪያ",
    norwegian: "ኖርወይኛ",
    pakistani: "ፓኪስታን",
    panamanian: "ፓናማኒያን",
    paraguayan: "ፓራጓይ",
    peruvian: "ፔሩቪያኛ",
    philippine: "ፊሊፒንስ",
    polish: "ፖሊሽ",
    portuguese: "ፖርቹጋልኛ",
    romanian: "ሮማንያን",
    russian: "ራሺያኛ",
    saudi: "ሳዑዲ",
    scottish: "ስኮትላንድኛ",
    senegalese: "ሴኔጋሌ",
    serbian: "ሰሪቢያን",
    singaporean: "ሲንጋፖር",
    slovak: "ስሎቫክ",
    southafrican: "ደቡብ አፍሪካ",
    korean: "ኮሪያኛ",
    spanish: "ስፓንኛ",
    srilankan: "ስሪላንካን",
    sudanese: "ሱዳናዊ",
    swedish: "ስዊድንኛ",
    swiss: "ስዊስ",
    syrian: "ሶሪያ",
    taiwanese: "ታይዋንኛ",
    tajikistani: "ታጂኪስታን",
    thai: "ታይ",
    tongan: "ቶንጋን",
    tunisian: "ቱኒዚያዊ",
    turkish: "ቱሪክሽ",
    ukrainian: "ዩክሬንያን",
    Emirati: "ኢሚራቲ",
    British: "ብሪቲሽ",
    american: "አሜሪካዊው ",
    uruguayan: "ኡራጓይኛ",
    venezuelan: "ቨንዙዋላ",
    vietnamese: "ቪትናሜሴ",
    welsh: "ዋልሽ",
    zambian: "ዛምቢያኛ",
    zimbabwean: "ዚምባብዌኛ",
  },
  passportNumber: "የፓስፖርት ቁጥር",
  email: "ኢሜል",
  dateOfBirth: "የትውልድ ቀን",
  sex: {
    label: "ጾታ",
    male: "ወንድ",
    female: "ሴት",
  },
  age: "እድሜ",
  region: {
    label: "ክልል",
    addisAbaba: "አዲስ አበባ",
    afar: "አፋር",
    amhara: "አማራ",
    benishangul: "ቤንሻንጉል ጉሙዝ",
    direDawa: "ድሬ ዳዋ",
    gambella: "ጋምቤላ",
    harari: "ሐረር",
    oromia: "ኦሮሚያ",
    somali: "ሶማሌ",
    southern: "የደቡብ ብሔር ብሔረሰቦችና ህዝቦች ክልል",
    tigray: "ትግራይ",
  },
  subcity: {
    label: "ክፍለ ከተማ",
    addisKetema: "አዲስ ከተማ",
    akakiKality: "አቃቂ ቃሊቲ",
    arada: "አራዳ",
    bole: "ቦሌ",
    gulele: "ጉለሌ",
    kirkos: "ቂርቆስ",
    kolfe: "ኮልፌ",
    lideta: "ልደታ",
    nifasSilkLafto: "ንፋስ ስልክ ላፍቶ",
    yeka: "የካ",
  },
  country: {
    label: "ሀገር",
    Afghanistan: "አፍጋኒስታን",
    ÅlandIslands: "የአላንድ ደሴቶች",
    Albania: "አልባኒያ",
    Algeria: "አልጄሪያ",
    AmericanSamoa: "አሜሪካዊ ሳሞአ",
    AndorrA: "አንዶራ",
    Angola: "አንጎላ",
    Anguilla: "አንጉላ",
    Antarctica: "አንታርክቲካ",
    AntiguaandBarbuda: "አንቲጉአ እና ባርቡዳ",
    Argentina: "አርጀንቲና",
    Armenia: "አርሜኒያ",
    Aruba: "አሩባ",
    Australia: "አውስትራሊያ",
    Austria: "ኦስትራ",
    Azerbaijan: "አዘርባጃን",
    Bahamas: "ባሐማስ",
    Bahrain: "ባሃሬን",
    Bangladesh: "ባንግላድሽ",
    Barbados: "ባርባዶስ",
    Belarus: "ቤላሩስ",
    Belgium: "ቤልጄም",
    Belize: "ቤሊዜ",
    Benin: "ቤኒኒ",
    Bermuda: "ቤርሙዳ",
    Bhutan: "በሓቱን",
    Bolivia: "ቦሊቪያ",
    BosniaandHerzegovina: "ቦስኒያ እና ሔርዞጎቪያ",
    Botswana: "ቦትስዋና",
    BouvetIsland: "ቡuች ደሴት",
    Brazil: "ብራዚል",
    BritishIndianOceanTerritory: "የብሪታንያ ህንድ ውቅያኖስ ግዛት",
    BruneiDarussalam: "ብሩኒ ዳርሳላም",
    Bulgaria: "ቡልጋሪያ",
    BurkinaFaso: "ቡርክናፋሶ",
    Burundi: "ቡሩንዲ",
    Cambodia: "ካምቦዲያ",
    Cameroon: "ካሜሩን",
    Canada: "ካናዳ",
    CapeVerde: "ኬፕ ቬሪዴ",
    CaymanIslands: "ኬይማን አይስላንድ",
    CentralAfricanRepublic: "ሴንትራል አፍሪካ ሪፑቢሊክ",
    Chad: "ቻድ",
    Chile: "ቺሊ",
    China: "ቻይና",
    ChristmasIsland: "የገና ደሴት",
    CocosKeelingIslands: "ኮኮስ (ኬሊንግ) ደሴቶች",
    Colombia: "ኮሎምቢያ",
    Comoros: "ኮሞሮስ",
    Congo: "ኮንጎ",
    CongoTheDemocraticRepublicofthe: "ኮንጎ ዲሞክራቲክ ሪፐብሊክ",
    CookIslands: "ኩክ አይስላንድስ",
    CostaRica: "ኮስታ ሪካ",
    CoteDIvoire: "ኮትዲቫር",
    Croatia: "ክሮሽያ",
    Cuba: "ኩባ",
    Cyprus: "ቆጵሮስ",
    CzechRepublic: "ቼክ ሪፐብሊክ",
    Denmark: "ዴንማሪክ",
    Djibouti: "ጅቡቲ",
    Dominica: "ዶሚኒካ",
    DominicanRepublic: "ዶሚኒካን ሪፐብሊክ",
    Ecuador: "ኢኳዶር",
    Egypt: "ግብጽ",
    ElSalvador: "ኤልሳልቫዶር",
    EquatorialGuinea: "ኢኳቶሪያል ጊኒ",
    Eritrea: "ኤርትሪያ",
    Estonia: "ኢስቶኒያ",
    Ethiopia: "ኢትዮጵያ",
    FalklandIslandsMalvinas: "የፎልክላንድ ደሴቶች (ማልቪናስ)",
    FaroeIslands: "ፋሮ ደሴቶች",
    Fiji: "ፊጂ",
    Finland: "ፊኒላንድ",
    France: "ፈረንሳይ",
    FrenchGuiana: "ፈረንሣይ ጉያና",
    FrenchPolynesia: "የፈረንሣይ ፖሊኔዥያ ",
    FrenchSouthernTerritories: "የፈረንሳይ ደቡባዊ ግዛቶች",
    Gabon: "ጋቦን",
    Gambia: "ጋምቢያ",
    Georgia: "ጆርጂያ",
    Germany: "ጀርመን",
    Ghana: "ጋና",
    Gibraltar: "ጊብራልታር",
    Greece: "ግሪክ",
    Greenland: "ግሪንላንድ",
    Grenada: "ግሪንዳዳ",
    Guadeloupe: "ጉደሎፕ",
    Guam: "ጉአሜ",
    Guatemala: "ጓቴማላ",
    Guernsey: "Ernርኒ",
    Guinea: "ጊኒ",
    GuineaBissau: "ጊኒ - ቢሳው",
    Guyana: "ጉያና",
    Haiti: "ሓይቲ",
    HeardIslandandMcdonaldIslands: "Ardርድ አይስላንድ እና ማክዶናልድ ደሴቶች",
    HolySeeVaticanCityState: "ቅዱስ ዕይታ (የቫቲካን ከተማ ግዛት)",
    Honduras: "ሆንዱራስ",
    HongKong: "ሆንግ ኮንግ",
    Hungary: "ሃንጋሪ",
    Iceland: "አይስላንድ",
    India: "ሕንድ",
    Indonesia: "ኢንዶኔዥያ",
    IranIslamicRepublicOf: "ኢራን , እስላማዊ ሪፐብሊክ",
    Iraq: "ኢራቅ",
    Ireland: "አይርላድ",
    IsleofMan: "አይስ የሰው",
    Israel: "እስራኤል",
    Italy: "ጣሊያን",
    Jamaica: "ጃማይካ",
    Japan: "ጃፓን",
    Jersey: "ጀርሲ",
    Jordan: "ዮርዳኖስ",
    Kazakhstan: "ካዛክስታን",
    Kenya: "ኬንያ",
    Kiribati: "ኪሪባቲ",
    KoreaDemocraticPeopleSRepublicof: "ኮሪያ , የዴሞክራሲያዊ ህዝብ ሪፐብሊክ",
    KoreaRepublicof: "ኮሪያ , ሪፐብሊክ",
    Kuwait: "ኵዌት",
    Kyrgyzstan: "ክይርጋዝስታን",
    LaoPeopleSDemocraticRepublic: "ላኦ ሰዎች ዲሞክራሲያዊ ሪፐብሊክ",
    Latvia: "ላቲቪያ",
    Lebanon: "ሊባኖስ",
    Lesotho: "ሌስቶ",
    Liberia: "ላይቤሪያ",
    LibyanArabJamahiriya: "ሊቢያ አረብ ጃማሂሪያ",
    Liechtenstein: "ለይችቴንስቴይን",
    Lithuania: "ሊቱአኒያ",
    Luxembourg: "ሉዘምቤርግ",
    Macao: "ማኮዎ",
    MacedoniaTheFormerYugoslavRepublicof: "መቄዶንያ , የቀድሞው የዩጎዝላቪያ ሪፐብሊክ",
    Madagascar: "ማዳጋስካር",
    Malawi: "ማላዊ",
    Malaysia: "ማሌዥያ",
    Maldives: "ማልዲቬስ",
    Mali: "ማሊ",
    Malta: "ማልታ",
    MarshallIslands: "ማርሻል አይስላንድ",
    Martinique: "ማርቲኒክ",
    Mauritania: "ሞሪታኒያ",
    Mauritius: "ሞሪሼስ",
    Mayotte: "ማዮትት",
    Mexico: "ሜክስኮ",
    MicronesiaFederatedStatesof: "ማይክሮኔዥያ , ፌዴራል መንግስታት",
    MoldovaRepublicof: "ሞልዶቫ , ሪፐብሊክ",
    Monaco: "ሞናኮ",
    Mongolia: "ሞንጎሊያ",
    Montserrat: "ሞንትሴራት",
    Morocco: "ሞሮኮ",
    Mozambique: "ሞዛምቢክ",
    Myanmar: "ማይንማር",
    Namibia: "ናምቢያ",
    Nauru: "ናኡሩ",
    Nepal: "ኔፓል",
    Netherlands: "ኔዜሪላንድ",
    NetherlandsAntilles: "ኔዘርላንድስ አንቲለስ",
    NewCaledonia: "ኒው ካሌዶኒያ",
    NewZealand: "ኒውዚላንድ",
    Nicaragua: "ኒካራጉአ",
    Niger: "ኒጀር",
    Nigeria: "ናይጄሪያ",
    Niue: "ኒይኡ",
    NorfolkIsland: "ኖርፎልክ አይስላንድስ",
    NorthernMarianaIslands: "የሰሜናዊ ማሪያና አይስላንድስ",
    Norway: "ኖርዌይ",
    Oman: "ኦማን",
    Pakistan: "ፓኪስታን",
    Palau: "ፓላኡ",
    PalestinianTerritoryOccupied: "የፍልስጤም ግዛት , የተያዘ",
    Panama: "ፓናማ",
    PapuaNewGuinea: "ፓፓዋ ኒው ጊኒ",
    Paraguay: "ፓራጓይ",
    Peru: "ፔሩ",
    Philippines: "ፊሊፕንሲ",
    Pitcairn: "ፒትካሪን",
    Poland: "ፖላንድ",
    Portugal: "ፖርቹጋል",
    PuertoRico: "ፖረቶ ሪኮ",
    Qatar: "ኳታር",
    Reunion: "ሬዩኒየን",
    Romania: "ሮማኒያ",
    RussianFederation: "የራሺያ ፌዴሬሽን",
    RWANDA: "ሩዋንዳ",
    SaintHelena: "ሰይንት ሄሌና",
    SaintKittsandNevis: "ሰይንት ኪትስ እና ኔቪስ",
    SaintLucia: "ሰይንት ሉካስ",
    SaintPierreandMiquelon: "ቅዱስ ፒየር እና ሚqueሎን",
    SaintVincentandtheGrenadines: "ሰይንት ቪንሴንት እና ጀሬናዲኔስ",
    Samoa: "ሳሞአ",
    SanMarino: "ሳን ማሪኖ",
    SaoTomeandPrincipe: "ሳኦ ቶሜ እና ፕሪንቺፔ",
    SaudiArabia: "ሳውዲ አረብያ",
    Senegal: "ሴኔጋል",
    SerbiaandMontenegro: "ሰርቢያ እና ሞንቴኔግሮ",
    Seychelles: "ሲሼልስ",
    SierraLeone: "ሰራሊዮን",
    Singapore: "ስንጋፖር",
    Slovakia: "ስሎቫኒካ",
    Slovenia: "ስሎቫኒያ",
    SolomonIslands: "የሰሎሞን አይስላንድስ",
    Somalia: "ሶማሊያ",
    SouthAfrica: "ደቡብ አፍሪካ",
    SouthGeorgiaandtheSouthSandwichIslands: "ደቡብ ጆርጂያ እና የደቡብ ሳንድዊች ደሴቶች",
    Spain: "ስፔን",
    SriLanka: "ስሪ ላንካ",
    Sudan: "ሱዳን",
    Suriname: "ሱሪናሜ",
    SvalbardandJanMayen: "ስቫልባር እና ጃን ማየን",
    Swaziland: "ስዋዝላድ",
    Sweden: "ስዊዲን",
    Switzerland: "ስዊዘሪላንድ",
    SyrianArabRepublic: "የሶሪያ አረብ ሪፐብሊክ",
    TaiwanProvinceofChina: "ታይዋን , የቻይና ግዛት",
    Tajikistan: "ታጂኪስታን",
    TanzaniaUnitedRepublicof: "ታንዛኒያ , የተባበሩት መንግስታት",
    Thailand: "ታይላንድ",
    TimorLeste: "ቲሞር-ሌስት",
    Togo: "መሄድ",
    Tokelau: "ቶኬላኡ",
    Tonga: "ቶንጋ",
    TrinidadandTobago: "ትሪኒዳድ እና ቶባጎ",
    Tunisia: "ቱንሲያ",
    Turkey: "ቱሪክ",
    Turkmenistan: "ቱርክሜኒስታን",
    TurksandCaicosIslands: "ቱርኮች እና የካኢኮስ ደሴቶች",
    Tuvalu: "ቱቫሉ",
    Uganda: "ኡጋንዳ",
    Ukraine: "ዩክሬን",
    UnitedArabEmirates: "ዩናይቲድ አራብ ኤሚራትስ",
    UnitedKingdom: "እንግሊዝ",
    UnitedStates: "የተባበሩት መንግስታት",
    UnitedStatesMinorOutlyingIslands: "የዩናይትድ ስቴትስ ትናንሽ ሩቅ ደሴቶች",
    Uruguay: "ኡራጋይ",
    Uzbekistan: "ኡዝቤክስታን",
    Vanuatu: "ቫኑአቱ",
    Venezuela: "ቨንዙዋላ",
    VietNam: "ቪትናም",
    VirginIslandsBritish: "ድንግል ደሴቶች , ብሪታንያ",
    VirginIslandsUS: "ድንግል ደሴቶች , አሜሪካ",
    WallisandFutuna: "ዎሊስ እና ፉቱና",
    WesternSahara: "ምዕራባዊ ሳሃራ",
    Yemen: "የመን",
    Zambia: "ዛምቢያ",
    Zimbabwe: "ዝምባቡዌ",
  },
  zone: "ዞን",
  woreda: "ወረዳ",
  kebele: "ቀበሌ",
  houseNumber: "የቤት ቁጥር",
  phoneNumber: "ስልክ ቁጥር",

  occupation: {
    label: "የሥራ መደብ",
    hcp: "የጤና ሰራተኛ",
    airport: "የአየር ማረፊያ ሰራተኛ",
    merchant: "ነጋዴ",
    other: "ሌላ",
  },
  occupationOther: "የሥራ መደብ ሌላ ከተመረጠ",
  callDate: "የጥሪ ቀን",
  // TODO
  callerType: {
    label: "የደዋይ ዓይነት",
    callerType1: "callerType1",
    callerType2: "callerType2",
  },
  caller: "የደዋይ",
  fever: "ትኩሳት",
  form: {
    label: "ቅጾች",
    community: "የማህበረሰብ",
    medicalCenters: "ጤና ተቋማት",
    portOfEntry: "ተጓዥ",
  },
  cough: "ሳል",
  fatigue: "የድካም ስሜት",
  headache: "ራስ ምታት",
  runnyNose: "የአፍንጫ ፍሳሽ(መዝረክረክ)/ንፍጥ",
  feelingUnwell: "ጤንነት መታወክ/ህመም መሰማት",
  underlyingConditions: "ቅድመ ነባር የጤና ሁኔታዎች",
  chronicLungDisease: "የመተንፈሻ አካላት በሽታዎች",
  heartDisease: "የልብ በሽታ",
  liverDisease: "የጉበት በሽታዎች",
  renalDisease: "የኩላሊት በሽታዎች",
  autoimmuneDisease: "የሰውነት ራስ የማጥቃት በሽታዎች / በሽታን የመቋቋም አቅም የሚቀንሱ መድሃኒቶች መውሰድ",
  cancer: "ካንሰር",
  diabetes: "የስኳር በሽታ",
  hiv: "ኤች አይ ቪ /ኤድስ",
  pregnancy: "እርግዝና",
  shortnessOfBreath: "የመተንፈስ ችግር",
  bodyPain: "የሰውነት ህመም",
  travelHistory: "የጉዞ ታሪክ",
  haveSex: "የወሲባዊ ግንኙነት",
  animalMarket: "የእንስሳት ገበያ ይሰራሉ/ጎብኝተዋል",
  healthFacility: "የጤና ተቋም ይሰራሉ/ጎብኝተዋል",
  receiverName: "የተሞላው በ...",
  source: "ምንጭ",
  yes: "አዎ",
  no: "አይ",
  formStatus: "",
  hotel: {
    label: "ሆቴል",
    skylight: "ስካይላይት ሆቴል",
    ghion: "ጊዮን ሆቴል",
    azzeman: "አዜማን ሆቴል",
    sapphire: "ሳፋየር ሆቴል",
    other: "ሌላ",
  },

  addDependent: "ጥገኛ (ኦች) ያክሉ",
  hotelOther: "ሆቴል ሌላ ከተመረጠ",
  formErrors: {
    empty: "ይህ ቦታ ባዶ መሆን አይችልም",
    numberOnly: "እባክዎ ቁጥር ብቻ ያስገቡ",
    email: "እባክዎ ትክክል ኢሜይል ያስገቡ",
    lengthAtMost100: "እባክዎ 100 ቃላት ብቻ ያስገቡ",
  },
  note: {
    lable: "ማስታወሻ",
    note1: "የ COVID ምልክቶች - 19 ትኩሳት , ደረቅ ሳል እና የትንፋሽ እጥረት ናቸው",
    note2:
      "ከላይ ከተዘረዘሩት ምልክቶች መካከል ከአንድ ወይም ከዚያ በላይ ከሆኑ ካጋጠሙዎት እራስዎን ችላ ብለው ለ 8335 ይደውሉ",
    note3: "እነዚህ ምልክቶች ያሉት ሰው ከተጠራጠሩ ወደ 8335 ለመደወል አያመንቱ",
    note4: "የበሽታው ምልክቶች ካለው ማንኛውም ሰው ርቀትዎን (ቢያንስ 1 ሜትር) ያርቁ",
  },
  travelFrom: "መነሻ",
  flightNumber: "የበረራ ቁጥር",
  seatNumber: "መቀመጫ ቁጥር",
  headerTitle: "የ COVID-19 ቅጾች",
  footerText: "የ COVID-19 ቅጾች",
  transitFrom: "ትራንዚት (ካለ)",
  healthFacilitiesApplicationForm: "የጤና ተቋማት ማመልከቻ ቅጽ",
  healthFacilitiesReportingFormForCOVID19: "የ COVID-19 ን ቅጽ የሚገልጽ የጤና አቅርቦቶች",
  generalInformation: "አጠቃላይ መረጃ",
  symptoms: "ምልክቶች",
  onlineSuspectForm: "የማህበረሰብ ምዝገባ ቅጽ",
  basicInformation: "መሰረታዊ መረጃ",
  address: "አድራሻ",
  passengerRegistrationForm: "የተጓዥ ምዝገባ ቅጽ",
  travelInfo: "የጉዞ መረጃ",
  dependentBasicInformation: "ጥገኛ መሠረታዊ መረጃ",
  passengerDependentsRegistrationForm: "የተጓዥ ጥገኛ ምዝገባ ቅጽ",
  dependents: "ጥገኛዎች",
  dependentsBasicInformation: "የጥገኛ መሰረታዊ መረጃ",
  submitDependent: "ጥገኛ ይመዝግቡ",
  submit: "ያስገቡ",
  formSubmittedSuccess: "ቅጽ ገብቷል",
  formSubmittedError: "ስህተት: ቅጽ ማስገባት አልተቻለም",
};
