import AddressValuesList from "./addres_values_am";

export default {
  preferredLanguage: {
    label: "ተመራጭ ቋንቋ",
    english: "እንግሊዘኛ",
    amharic: "አማርኛ",
    oromo: "ኦሮምኛ",
  },
  firstName: "ስም",
  middleName: "የአባት ስም",
  lastName: "የአያት ስም",
  nationality: {
    label: "ዜግነት",
    value: AddressValuesList.nationality,
  },
  passportNumber: "የፓስፖርት ቁጥር",
  email: "ኢሜል",
  dateOfBirth: "የትውልድ ቀን",
  gender: {
    label: "ጾታ",
    male: "ወንድ",
    female: "ሴት",
  },
  age: "እድሜ",
  region: {
    label: "ክልል",
    value: AddressValuesList.region,
  },
  city: {
    label: "ከተማ",
    value: AddressValuesList.city,
  },
  subcity: {
    label: "ክፍለ ከተማ",
    value: AddressValuesList.subcity,
  },
  country: {
    label: "ሀገር",
    value: AddressValuesList.country,
  },
  zone: "ዞን",
  woreda: "ወረዳ",
  kebele: "ቀበሌ",
  houseNumber: "የቤት ቁጥር",
  phoneNumber: "ስልክ ቁጥር",
  postalCode: "የፖስታ ሳጥን ቁጥር",
  occupation: {
    label: "የሥራ መደብ",
    hcp: "የጤና ሰራተኛ",
    airport: "የአየር ማረፊያ ሰራተኛ",
    merchant: "ነጋዴ",
    other: "ሌላ",
  },
  occupationOther: "የሥራ መደብ ሌላ ከተመረጠ",
  callDate: "የጥሪ ቀን",
  // TODO
  callerType: {
    label: "የደዋይ ዓይነት",
    callerType1: "callerType1",
    callerType2: "callerType2",
  },
  caller: "የደዋይ",
  fever: "ትኩሳት",
  form: {
    label: "ቅጾች",
    community: "የማህበረሰብ",
    medicalCenters: "ጤና ተቋማት",
    portOfEntry: "ተጓዥ",
  },
  cough: "ሳል",
  fatigue: "የድካም ስሜት",
  headache: "ራስ ምታት",
  runnyNose: "የአፍንጫ ፍሳሽ(መዝረክረክ)/ንፍጥ",
  feelingUnwell: "ጤንነት መታወክ/ህመም መሰማት",
  underlyingConditions: "ቅድመ ነባር የጤና ሁኔታዎች",
  chronicLungDisease: "የመተንፈሻ አካላት በሽታዎች",
  heartDisease: "የልብ በሽታ",
  liverDisease: "የጉበት በሽታዎች",
  renalDisease: "የኩላሊት በሽታዎች",
  autoimmuneDisease: "የሰውነት ራስ የማጥቃት በሽታዎች / በሽታን የመቋቋም አቅም የሚቀንሱ መድሃኒቶች መውሰድ",
  cancer: "ካንሰር",
  diabetes: "የስኳር በሽታ",
  hiv: "ኤች አይ ቪ /ኤድስ",
  pregnancy: "እርግዝና",
  shortnessOfBreath: "የመተንፈስ ችግር",
  bodyPain: "የሰውነት ህመም",
  hasRecentlyTraveled: "የጉዞ ታሪክ",
  haveSex: "የወሲባዊ ግንኙነት",
  animalMarket: "የእንስሳት ገበያ ይሰራሉ/ጎብኝተዋል",
  worksAtOrVisitedHealthFacility: "የጤና ተቋም ይሰራሉ/ጎብኝተዋል",
  receiverName: "የተሞላው በ...",
  yes: "አዎ",
  no: "አይ",
  formStatus: "",
  hotel: {
    label: "ሆቴል",
    skylight: "ስካይላይት ሆቴል",
    ghion: "ጊዮን ሆቴል",
    azzeman: "አዜማን ሆቴል",
    sapphire: "ሳፋየር ሆቴል",
    other: "ሌላ",
  },

  addDependent: "ጥገኛ (ኦች) ያክሉ",
  hotelOther: "ሆቴል ሌላ ከተመረጠ",
  formErrors: {
    empty: "ይህ ቦታ ባዶ መሆን አይችልም",
    numberOnly: "እባክዎ ቁጥር ብቻ ያስገቡ",
    email: "እባክዎ ትክክል ኢሜይል ያስገቡ",
    lengthAtMost100: "እባክዎ 100 ቃላት ብቻ ያስገቡ",
  },
  note: {
    lable: "ማስታወሻ",
    note1: "የ COVID ምልክቶች - 19 ትኩሳት , ደረቅ ሳል እና የትንፋሽ እጥረት ናቸው",
    note2:
      "ከላይ ከተዘረዘሩት ምልክቶች መካከል ከአንድ ወይም ከዚያ በላይ ከሆኑ ካጋጠሙዎት እራስዎን ችላ ብለው ለ 8335 ይደውሉ",
    note3: "እነዚህ ምልክቶች ያሉት ሰው ከተጠራጠሩ ወደ 8335 ለመደወል አያመንቱ",
    note4: "የበሽታው ምልክቶች ካለው ማንኛውም ሰው ርቀትዎን (ቢያንስ 1 ሜትር) ያርቁ",
  },
  travelFromCountry: "ጉዞ መነሻ ሀገር",
  source: "ምንጭ",
  finalTransitCountry: "የመጨረሻ የትራንስፖርት ሀገር",
  flightNumber: "የበረራ ቁጥር",
  seatNumber: "መቀመጫ ቁጥር",
  headerTitle: "የ COVID-19 ቅጾች",
  footerText: "የ COVID-19 ቅጾች",
  transitFrom: "ትራንዚት (ካለ)",
  healthFacilitiesApplicationForm: "የጤና ተቋማት ማመልከቻ ቅጽ",
  healthFacilitiesReportingFormForCOVID19: "የ COVID-19 ን ቅጽ የሚገልጽ የጤና አቅርቦቶች",
  generalInformation: "አጠቃላይ መረጃ",
  riskFromContact: "ከንክኪ የሚመጣ/የሚመነጭ ተጋላጭነት/አደጋ",
  symptoms: "ምልክቶች",
  onlineSuspectForm: "የማህበረሰብ ምዝገባ ቅጽ",
  basicInformation: "መሰረታዊ መረጃ",
  address: "አድራሻ",

  contactInformation: "የመገኛ አድራሻ",
  passengerRegistrationForm: "የተጓዥ ምዝገባ ቅጽ",
  travelInfo: "የጉዞ መረጃ",
  dependentBasicInformation: "ጥገኛ መሠረታዊ መረጃ",
  passengerDependentsRegistrationForm: "የተጓዥ ጥገኛ ምዝገባ ቅጽ",
  dependents: "ጥገኛዎች",
  dependentsBasicInformation: "የጥገኛ መሰረታዊ መረጃ",
  submitDependent: "ጥገኛ ይመዝግቡ",
  submit: "ያስገቡ",
  formSubmittedSuccess: "ቅጽ ገብቷል",
  formSubmittedError: "ስህተት: ቅጽ ማስገባት አልተቻለም",
  contactWithSuspected: "ከተጠራጠረ ጋር ንክኪ",
  contactWithConfirmed: "ከተረጋገጠ ጋር ንክኪ",
  governmentIssuedId: "የመንግስት የተሰጠ መታወቂያ",
  relationshipToPassenger: "ከተሳፋሪ ጋር ያለዉ ግንኙነት",
};
