export default {
  preferredLanguage: {
    label: "Preferred Language",
    english: "English",
    amharic: "Amharic",
    oromo: "Afan Oromo",
  },
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  age: "Age",
  email: "Email",
  dateOfBirth: "Date of Birth",
  country: {
    label: "Country",
    Afghanistan: "Afghanistan",
    ÅlandIslands: "Åland Islands",
    Albania: "Albania",
    Algeria: "Algeria",
    AmericanSamoa: "American Samoa",
    AndorrA: "AndorrA",
    Angola: "Angola",
    Anguilla: "Anguilla",
    Antarctica: "Antarctica",
    AntiguaandBarbuda: "Antigua and Barbuda",
    Argentina: "Argentina",
    Armenia: "Armenia",
    Aruba: "Aruba",
    Australia: "Australia",
    Austria: "Austria",
    Azerbaijan: "Azerbaijan",
    Bahamas: "Bahamas",
    Bahrain: "Bahrain",
    Bangladesh: "Bangladesh",
    Barbados: "Barbados",
    Belarus: "Belarus",
    Belgium: "Belgium",
    Belize: "Belize",
    Benin: "Benin",
    Bermuda: "Bermuda",
    Bhutan: "Bhutan",
    Bolivia: "Bolivia",
    BosniaandHerzegovina: "Bosnia and Herzegovina",
    Botswana: "Botswana",
    BouvetIsland: "Bouvet Island",
    Brazil: "Brazil",
    BritishIndianOceanTerritory: "British Indian Ocean Territory",
    BruneiDarussalam: "Brunei Darussalam",
    Bulgaria: "Bulgaria",
    BurkinaFaso: "Burkina Faso",
    Burundi: "Burundi",
    Cambodia: "Cambodia",
    Cameroon: "Cameroon",
    Canada: "Canada",
    CapeVerde: "Cape Verde",
    CaymanIslands: "Cayman Islands",
    CentralAfricanRepublic: "Central African Republic",
    Chad: "Chad",
    Chile: "Chile",
    China: "China",
    ChristmasIsland: "Christmas Island",
    CocosKeelingIslands: "Cocos (Keeling) Islands",
    Colombia: "Colombia",
    Comoros: "Comoros",
    Congo: "Congo",
    CongoTheDemocraticRepublicofthe: "Congo, The Democratic Republic of the",
    CookIslands: "Cook Islands",
    CostaRica: "Costa Rica",
    CoteDIvoire: "Cote D'Ivoire",
    Croatia: "Croatia",
    Cuba: "Cuba",
    Cyprus: "Cyprus",
    CzechRepublic: "Czech Republic",
    Denmark: "Denmark",
    Djibouti: "Djibouti",
    Dominica: "Dominica",
    DominicanRepublic: "Dominican Republic",
    Ecuador: "Ecuador",
    Egypt: "Egypt",
    ElSalvador: "El Salvador",
    EquatorialGuinea: "Equatorial Guinea",
    Eritrea: "Eritrea",
    Estonia: "Estonia",
    Ethiopia: "Ethiopia",
    FalklandIslandsMalvinas: "Falkland Islands (Malvinas)",
    FaroeIslands: "Faroe Islands",
    Fiji: "Fiji",
    Finland: "Finland",
    France: "France",
    FrenchGuiana: "French Guiana",
    FrenchPolynesia: "French Polynesia",
    FrenchSouthernTerritories: "French Southern Territories",
    Gabon: "Gabon",
    Gambia: "Gambia",
    Georgia: "Georgia",
    Germany: "Germany",
    Ghana: "Ghana",
    Gibraltar: "Gibraltar",
    Greece: "Greece",
    Greenland: "Greenland",
    Grenada: "Grenada",
    Guadeloupe: "Guadeloupe",
    Guam: "Guam",
    Guatemala: "Guatemala",
    Guernsey: "Guernsey",
    Guinea: "Guinea",
    GuineaBissau: "Guinea-Bissau",
    Guyana: "Guyana",
    Haiti: "Haiti",
    HeardIslandandMcdonaldIslands: "Heard Island and Mcdonald Islands",
    HolySeeVaticanCityState: "Holy See (Vatican City State)",
    Honduras: "Honduras",
    HongKong: "Hong Kong",
    Hungary: "Hungary",
    Iceland: "Iceland",
    India: "India",
    Indonesia: "Indonesia",
    IranIslamicRepublicOf: "Iran, Islamic Republic Of",
    Iraq: "Iraq",
    Ireland: "Ireland",
    IsleofMan: "Isle of Man",
    Israel: "Israel",
    Italy: "Italy",
    Jamaica: "Jamaica",
    Japan: "Japan",
    Jersey: "Jersey",
    Jordan: "Jordan",
    Kazakhstan: "Kazakhstan",
    Kenya: "Kenya",
    Kiribati: "Kiribati",
    KoreaDemocraticPeopleSRepublicof: "Korea, Democratic People'S Republic of",
    KoreaRepublicof: "Korea, Republic of",
    Kuwait: "Kuwait",
    Kyrgyzstan: "Kyrgyzstan",
    LaoPeopleSDemocraticRepublic: "Lao People'S Democratic Republic",
    Latvia: "Latvia",
    Lebanon: "Lebanon",
    Lesotho: "Lesotho",
    Liberia: "Liberia",
    LibyanArabJamahiriya: "Libyan Arab Jamahiriya",
    Liechtenstein: "Liechtenstein",
    Lithuania: "Lithuania",
    Luxembourg: "Luxembourg",
    Macao: "Macao",
    MacedoniaTheFormerYugoslavRepublicof:
      "Macedonia, The Former Yugoslav Republic of",
    Madagascar: "Madagascar",
    Malawi: "Malawi",
    Malaysia: "Malaysia",
    Maldives: "Maldives",
    Mali: "Mali",
    Malta: "Malta",
    MarshallIslands: "Marshall Islands",
    Martinique: "Martinique",
    Mauritania: "Mauritania",
    Mauritius: "Mauritius",
    Mayotte: "Mayotte",
    Mexico: "Mexico",
    MicronesiaFederatedStatesof: "Micronesia, Federated States of",
    MoldovaRepublicof: "Moldova, Republic of",
    Monaco: "Monaco",
    Mongolia: "Mongolia",
    Montserrat: "Montserrat",
    Morocco: "Morocco",
    Mozambique: "Mozambique",
    Myanmar: "Myanmar",
    Namibia: "Namibia",
    Nauru: "Nauru",
    Nepal: "Nepal",
    Netherlands: "Netherlands",
    NetherlandsAntilles: "Netherlands Antilles",
    NewCaledonia: "New Caledonia",
    NewZealand: "New Zealand",
    Nicaragua: "Nicaragua",
    Niger: "Niger",
    Nigeria: "Nigeria",
    Niue: "Niue",
    NorfolkIsland: "Norfolk Island",
    NorthernMarianaIslands: "Northern Mariana Islands",
    Norway: "Norway",
    Oman: "Oman",
    Pakistan: "Pakistan",
    Palau: "Palau",
    PalestinianTerritoryOccupied: "Palestinian Territory, Occupied",
    Panama: "Panama",
    PapuaNewGuinea: "Papua New Guinea",
    Paraguay: "Paraguay",
    Peru: "Peru",
    Philippines: "Philippines",
    Pitcairn: "Pitcairn",
    Poland: "Poland",
    Portugal: "Portugal",
    PuertoRico: "Puerto Rico",
    Qatar: "Qatar",
    Reunion: "Reunion",
    Romania: "Romania",
    RussianFederation: "Russian Federation",
    RWANDA: "RWANDA",
    SaintHelena: "Saint Helena",
    SaintKittsandNevis: "Saint Kitts and Nevis",
    SaintLucia: "Saint Lucia",
    SaintPierreandMiquelon: "Saint Pierre and Miquelon",
    SaintVincentandtheGrenadines: "Saint Vincent and the Grenadines",
    Samoa: "Samoa",
    SanMarino: "San Marino",
    SaoTomeandPrincipe: "Sao Tome and Principe",
    SaudiArabia: "Saudi Arabia",
    Senegal: "Senegal",
    SerbiaandMontenegro: "Serbia and Montenegro",
    Seychelles: "Seychelles",
    SierraLeone: "Sierra Leone",
    Singapore: "Singapore",
    Slovakia: "Slovakia",
    Slovenia: "Slovenia",
    SolomonIslands: "Solomon Islands",
    Somalia: "Somalia",
    SouthAfrica: "South Africa",
    SouthGeorgiaandtheSouthSandwichIslands:
      "South Georgia and the South Sandwich Islands",
    Spain: "Spain",
    SriLanka: "Sri Lanka",
    Sudan: "Sudan",
    Suriname: "Suriname",
    SvalbardandJanMayen: "Svalbard and Jan Mayen",
    Swaziland: "Swaziland",
    Sweden: "Sweden",
    Switzerland: "Switzerland",
    SyrianArabRepublic: "Syrian Arab Republic",
    TaiwanProvinceofChina: "Taiwan, Province of China",
    Tajikistan: "Tajikistan",
    TanzaniaUnitedRepublicof: "Tanzania, United Republic of",
    Thailand: "Thailand",
    TimorLeste: "Timor-Leste",
    Togo: "Togo",
    Tokelau: "Tokelau",
    Tonga: "Tonga",
    TrinidadandTobago: "Trinidad and Tobago",
    Tunisia: "Tunisia",
    Turkey: "Turkey",
    Turkmenistan: "Turkmenistan",
    TurksandCaicosIslands: "Turks and Caicos Islands",
    Tuvalu: "Tuvalu",
    Uganda: "Uganda",
    Ukraine: "Ukraine",
    UnitedArabEmirates: "United Arab Emirates",
    UnitedKingdom: "United Kingdom",
    UnitedStates: "United States",
    UnitedStatesMinorOutlyingIslands: "United States Minor Outlying Islands",
    Uruguay: "Uruguay",
    Uzbekistan: "Uzbekistan",
    Vanuatu: "Vanuatu",
    Venezuela: "Venezuela",
    VietNam: "Viet Nam",
    VirginIslandsBritish: "Virgin Islands, British",
    VirginIslandsUS: "Virgin Islands, U.S.",
    WallisandFutuna: "Wallis and Futuna",
    WesternSahara: "Western Sahara",
    Yemen: "Yemen",
    Zambia: "Zambia",
    Zimbabwe: "Zimbabwe",
  },
  city: "City",
  region: {
    label: "Region",
    addisAbaba: "Addis Ababa",
    afar: "Afar",
    amhara: "Amhara",
    benishangul: "Benishangul-Gumuz",
    direDawa: "Dire Dawa",
    gambella: "Gambella",
    harari: "Harari",
    oromia: "Oromia",
    somali: "Somali",
    southern: "Southern Nations, Nationalities, and Peoples",
    tigray: "Tigray",
  },
  subcity: {
    label: "Sub City",
    addisKetema: "Addis Ketema",
    akakiKality: "Akaki Kality",
    arada: "Arada",
    bole: "Bole",
    gulele: "Gulele",
    kirkos: "Kirkos",
    kolfe: "Kolfe",
    lideta: "Lideta",
    nifasSilkLafto: "Nifas Silk Lafto",
    yeka: "Yeka",
  },
  postalCode: "Postal Code",
  street: "Street",
  building: "Building",
  zone: "Zone",
  houseNumber: "House Number",
  nationality: {
    label: "Nationality",
    afghan: "Afghan",
    albanian: "Albanian",
    algerian: "Algerian",
    american: "American ",
    argentinian: "Argentine",
    australian: "Australian",
    austrian: "Austrian",
    bangladeshi: "Bangladeshi",
    batswana: "Batswana",
    belgian: "Belgian",
    bolivian: "Bolivian",
    brazilian: "Brazilian",
    British: "British",
    bulgarian: "Bulgarian",
    cambodian: "Cambodian",
    cameroonian: "Cameroonian",
    canadian: "Canadian",
    chilean: "Chilean",
    chinese: "Chinese",
    colombian: "Colombian",
    costaRican: "Costa Rican",
    croatian: "Croatian",
    cuban: "Cuban",
    czech: "Czech",
    danish: "Danish",
    dominican: "Dominican",
    dutch: "Dutch",
    ecuadorian: "Ecuadorian",
    egyptian: "Egyptian",
    Emirati: "Emirati",
    english: "English",
    estonian: "Estonian",
    ethiopian: "Ethiopian",
    fijian: "Fijian",
    finnish: "Finnish",
    french: "French",
    german: "German",
    ghanaian: "Ghanaian",
    greek: "Greek",
    guatemalan: "Guatemalan",
    haitian: "Haitian",
    honduran: "Honduran",
    hungarian: "Hungarian",
    icelandic: "Icelandic",
    indian: "Indian",
    indonesian: "Indonesian",
    iranian: "Iranian",
    iraqi: "Iraqi",
    irish: "Irish",
    israeli: "Israeli",
    italian: "Italian",
    jamaican: "Jamaican",
    japanese: "Japanese",
    jordanian: "Jordanian",
    kenyan: "Kenyan",
    korean: "Korean",
    kuwaiti: "Kuwaiti",
    lao: "Lao",
    latvian: "Latvian",
    lebanese: "Lebanese",
    libyan: "Libyan",
    lithuanian: "Lithuanian",
    malagasy: "Malagasy",
    malaysian: "Malaysian",
    malian: "Malian",
    maltese: "Maltese",
    mexican: "Mexican",
    mongolian: "Mongolian",
    moroccan: "Moroccan",
    mozambican: "Mozambican",
    namibian: "Namibian",
    nepalese: "Nepalese",
    newzealand: "New Zealand",
    nicaraguan: "Nicaraguan",
    nigerian: "Nigerian",
    norwegian: "Norwegian",
    pakistani: "Pakistani",
    panamanian: "Panamanian",
    paraguayan: "Paraguayan",
    peruvian: "Peruvian",
    philippine: "Philippine",
    polish: "Polish",
    portuguese: "Portuguese",
    romanian: "Romanian",
    russian: "Russian",
    salvadorian: "Salvadorian",
    saudi: "Saudi",
    scottish: "Scottish",
    senegalese: "Senegalese",
    serbian: "Serbian",
    singaporean: "Singaporean",
    slovak: "Slovak",
    southafrican: "South African",
    spanish: "Spanish",
    srilankan: "Sri Lankan",
    sudanese: "Sudanese",
    swedish: "Swedish",
    swiss: "Swiss",
    syrian: "Syrian",
    taiwanese: "Taiwanese",
    tajikistani: "Tajikistani",
    thai: "Thai",
    tongan: "Tongan",
    tunisian: "Tunisian",
    turkish: "Turkish",
    ukrainian: "Ukrainian",
    uruguayan: "Uruguayan",
    venezuelan: "Venezuelan",
    vietnamese: "Vietnamese",
    welsh: "Welsh",
    zambian: "Zambian",
    zimbabwean: "Zimbabwean",
  },
  passportNumber: "Passport Number",
  phoneNumber: "Phone Number",
  occupation: {
    label: "Occupation",
    hcp: "HCP",
    merchant: "Merchant (Animal)",
    airport: "Airport",
    other: "Other",
  },
  occupationOther: "Occupation if other was choosen",
  gender: {
    label: "Gender",
    male: "Male",
    female: "Female",
  },
  callerType: {
    label: "Caller Type",
    callerType1: "callerType1",
    callerType2: "callerType2",
  },
  caller: "Caller",
  receiverName: "Receiver Name",
  hotel: {
    label: "Hotel",
    skylight: "Skylight Hotel",
    ghion: "Ghion Hotel",
    azzeman: "Azzeman Hotel",
    sapphire: "Sapphire Hotel",
    other: "Other",
  },
  hotelOther: "Hotel if other was choosen",
  callDate: "Call Date",
  yes: "Yes",
  no: "No",
  submit: "Submit",
  submitDependent: "Submit Dependent",
  formSubmittedSuccess: "Form Submitted",
  formSubmittedError: "ERROR: Unable to Submit Form",
  travelFromCountry: "Travel From",
  finalTransitCountry: "Final Transit Country",
  source: "Source",
  hasRecentlyTraveled: "Has a Recent Travel History",
  contactWithSuspected: "Contact With Suspected",
  contactWithConfirmed: "Contact With Confirmed",
  worksAtOrVisitedHealthFacility: "Had Visited a Health Facility",
  transitFrom: "Transit (if any)",
  flightNumber: "Flight Number",
  seatNumber: "Seat Number",
  addDependent: "Add Dependent(s)",
  headerTitle: "COVID-19 Surveillance Forms",
  footerText: "COVID-19 Surveillance Forms",
  form: {
    label: "Forms",
    community: "Community",
    medicalCenters: "Medical Centers",
    portOfEntry: "Passengers",
  },
  fever: "Fever",
  cough: "Cough",
  headache: "Headache",
  fatigue: "Fatigue/tiredness",
  runnyNose: "Runny Nose",
  feelingUnwell: "Feeling Unwell",
  shortnessOfBreath: "Shortness Of Breath",
  bodyPain: "Body Pain",
  underlyingConditions: "Underlying Health conditions",
  chronicLungDisease: "Chronic respiratory/lung disease",
  heartDisease: "Heart disease",
  liverDisease: "Liver diseases",
  renalDisease: "Renal diseases",
  autoimmuneDisease: "Autoimmune diseases/taking immunosuppressive medication",
  cancer: "Cancer ",
  diabetes: "Diabetes",
  hiv: "HIV/AIDS",
  pregnancy: "Pregnancy",
  note: {
    lable: "Note",
    note1:
      "Symptoms of COVID - 19 are fever, dry cough and shortness of breath.",
    note2:
      "If you experience one or more of the above symptoms, isolate yourself and call 8335.",
    note3:
      "If you suspect someone else has these symptoms, don't hesitate to call to 8335.",
    note4: "Keep your distance (minimum 1 Meter) from anyone who has symptoms.",
  },
  formErrors: {
    empty: "This field can not be empty",
    numberOnly: "This field is for number only",
    email: "Email address must be valid",
    lengthAtMost100: "100 or few characters please",
  },
  healthFacilitiesApplicationForm: "Health Facilities Application Form",
  healthFacilitiesReportingFormForCOVID19:
    "Health Facilities Reporting Form For COVID-19",
  generalInformation: "GENERAL INFORMATION",
  riskFromContact: "Risk From Contact",
  symptoms: "SYMPTOMS",
  onlineSuspectForm: "Community Reporting Form",
  basicInformation: "Basic Information",
  address: "Address",
  contactInformation: "Contact Information",
  passengerRegistrationForm: "Passenger Registration Form",
  travelInfo: "Travel Info",
  dependentBasicInformation: "Dependent's Basic Information",
  passengerDependentsRegistrationForm: "Passenger Dependents Registration Form",
  dependents: "Dependents",
  dependentsBasicInformation: "Dependent's Basic Information",
  governmentIssuedId: "Government Issued ID",
  relationshipToPassenger: "Relationship To Passenger",
};
