import AddressValuesList from "./addres_values_en";
export default {
  preferredLanguage: {
    label: "Preferred Language",
    english: "English",
    amharic: "Amharic",
    oromo: "Afan Oromo",
  },
  firstName: "First Name",
  middleName: "Middle Name",
  lastName: "Last Name",
  age: "Age",
  email: "Email",
  dateOfBirth: "Date of Birth",
  country: {
    label: "Country",
    value: AddressValuesList.country,
  },
  city: {
    label: "City",
    value: AddressValuesList.city,
  },
  region: {
    label: "Region",
    value: AddressValuesList.region,
  },
  subcity: {
    label: "Sub City",
    value: AddressValuesList.subcity,
  },
  postalCode: "Postal Code",
  street: "Street",
  building: "Building",
  zone: "Zone",
  woreda: "Woreda",
  kebele: "Kebele",
  houseNumber: "House Number",
  nationality: {
    label: "Nationality",
    value: AddressValuesList.nationality,
  },
  passportNumber: "Passport Number",
  phoneNumber: "Phone Number",
  occupation: {
    label: "Occupation",
    hcp: "HCP",
    merchant: "Merchant (Animal)",
    airport: "Airport",
    other: "Other",
  },
  occupationOther: "Occupation if other was choosen",
  gender: {
    label: "Gender",
    male: "Male",
    female: "Female",
  },
  callerType: {
    label: "Caller Type",
    callerType1: "callerType1",
    callerType2: "callerType2",
  },
  caller: "Caller",
  receiverName: "Receiver Name",
  hotel: {
    label: "Hotel",
    skylight: "Skylight Hotel",
    ghion: "Ghion Hotel",
    azzeman: "Azzeman Hotel",
    sapphire: "Sapphire Hotel",
    other: "Other",
  },
  hotelOther: "Hotel if other was choosen",
  callDate: "Call Date",
  yes: "Yes",
  no: "No",
  submit: "Submit",
  submitDependent: "Submit Dependent",
  formSubmittedSuccess: "Form Submitted",
  formSubmittedError: "ERROR: Unable to Submit Form",
  travelFromCountry: "Travel From",
  finalTransitCountry: "Final Transit Country",
  source: "Source",
  hasRecentlyTraveled: "Has a Recent Travel History",
  contactWithSuspected: "Contact With Suspected",
  contactWithConfirmed: "Contact With Confirmed",
  worksAtOrVisitedHealthFacility: "Had Visited a Health Facility",
  transitFrom: "Transit (if any)",
  flightNumber: "Flight Number",
  seatNumber: "Seat Number",
  addDependent: "Add Dependent(s)",
  headerTitle: "COVID-19 Surveillance Forms",
  footerText: "COVID-19 Surveillance Forms",
  form: {
    label: "Forms",
    community: "Community",
    medicalCenters: "Medical Centers",
    portOfEntry: "Passengers",
  },
  fever: "Fever",
  cough: "Cough",
  headache: "Headache",
  fatigue: "Fatigue/tiredness",
  runnyNose: "Runny Nose",
  feelingUnwell: "Feeling Unwell",
  shortnessOfBreath: "Shortness Of Breath",
  bodyPain: "Body Pain",
  underlyingConditions: "Underlying Health conditions",
  chronicLungDisease: "Chronic respiratory/lung disease",
  heartDisease: "Heart disease",
  liverDisease: "Liver diseases",
  renalDisease: "Renal diseases",
  autoimmuneDisease: "Autoimmune diseases/taking immunosuppressive medication",
  cancer: "Cancer ",
  diabetes: "Diabetes",
  hiv: "HIV/AIDS",
  pregnancy: "Pregnancy",
  note: {
    lable: "Note",
    note1:
      "Symptoms of COVID - 19 are fever, dry cough and shortness of breath.",
    note2:
      "If you experience one or more of the above symptoms, isolate yourself and call 8335.",
    note3:
      "If you suspect someone else has these symptoms, don't hesitate to call to 8335.",
    note4: "Keep your distance (minimum 1 Meter) from anyone who has symptoms.",
  },
  formErrors: {
    empty: "This field can not be empty",
    numberOnly: "This field is for number only",
    email: "Email address must be valid",
    lengthAtMost100: "100 or few characters please",
  },
  healthFacilitiesApplicationForm: "Health Facilities Application Form",
  healthFacilitiesReportingFormForCOVID19:
    "Health Facilities Reporting Form For COVID-19",
  generalInformation: "GENERAL INFORMATION",
  riskFromContact: "Risk From Contact",
  symptoms: "SYMPTOMS",
  onlineSuspectForm: "Community Reporting Form",
  basicInformation: "Basic Information",
  address: "Address",
  contactInformation: "Contact Information",
  passengerRegistrationForm: "Passenger Registration Form",
  travelInfo: "Travel Info",
  dependentBasicInformation: "Dependent's Basic Information",
  passengerDependentsRegistrationForm: "Passenger Dependents Registration Form",
  dependents: "Dependents",
  dependentsBasicInformation: "Dependent's Basic Information",
  governmentIssuedId: "Government Issued ID",
  relationshipToPassenger: "Relationship To Passenger",
};
